title: "<p align='center'>Marta Santos</p>"

logo: "/images/picture.jpg"

description: >
  <p align="center">
    <a href='pdf/resume.pdf'>Resume</a> |
    <a href='https://www.linkedin.com/in/marta-santos-214043224/'>LinkedIn</a> |
    <a href='https://github.com/martadsantos'>GitHub</a>
  </p>

  <p class="site-description">
    Industrial Engineering and Management graduate from the University of Porto, with hands-on experience in <strong>data science</strong>, <strong>machine learning</strong>, and <strong>data visualization</strong>.
  
    <br><br>
    Currently a <strong>tech consultant at Deloitte</strong>, where I develop <strong>data-driven solutions</strong>, including <strong>predictive models</strong>, <strong>dashboards</strong>, and <strong>resource estimation tools</strong>.
  
    <br><br>
    Passionate about applying data to real-world problems, I'm now aiming to <strong>deepen my expertise in Data Science</strong> and expand my skills in <strong>advanced analytics</strong>.
  </p>


