title: <p align="center"> Marta Santos </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/marta-santos-214043224/">LinkedIn</a> |
  <a href="https://github.com/martadsantos">GitHub</a>
  </p>
  
  <p align="justify">
  Industrial Engineering and Management graduate from the University of Porto with hands-on experience in data science, machine learning, and data visualization and with a strong analytical mindset and a growing focus on data science. Currently working in the SAP Analytics team at Deloitte, where I build data-driven solutions to support strategic decision-making. I have experience in developing predictive models, creating performance dashboards, and estimating resource needs based on process data.
  
  <br><br>
  
  Passionate about solving real-world problems through data, I’m now fully committed to transitioning into a Data Scientist role and expanding my skills in machine learning and advanced analytics.

  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
