title: "<p align='center'>Marta Santos</p>"

logo: "/images/picture.jpg"

description: >
  <p align="center">
    <a href='pdf/resume.pdf'>Resume</a> |
    <a href='https://www.linkedin.com/in/marta-santos-214043224/'>LinkedIn</a> |
    <a href='https://github.com/martadsantos'>GitHub</a>
  </p>

  <p class="site-description">
  Industrial Engineering and Management graduate from the University of Porto, with extensive experience in data science, machine learning, and data visualization.
  Currently a tech consultant at Deloitte, developing data-driven solutions that support strategic decision-making.

  <br><br>
  Passionate about leveraging data to solve complex business challenges, I am focused on deepening my expertise in Data Science, with a particular emphasis on machine learning and predictive analytics.
  </p>




