title: "<p align='center'>Marta Santos</p>"

logo: "/images/picture.jpg"

description: >
  <p align="center">
    <a href='pdf/resume.pdf'>Resume</a> |
    <a href='https://www.linkedin.com/in/marta-santos-214043224/'>LinkedIn</a> |
    <a href='https://github.com/martadsantos'>GitHub</a>
  </p>

  <p class="site-description">
  Industrial Engineering and Management graduate from the University of Porto, with hands-on experience in data science, machine learning, and data visualization.
  Currently a tech consultant at Deloitte, where I develop data-driven solutions to support strategic decision-making.

  <br><br>
  Passionate about applying data to real-world problems, I'm now aiming to deepen my expertise in Data Science and expand my skills in advanced analytics.
  </p>



